### PR TITLE
Integrating netcode

### PR DESCRIPTION
**Pull request by matthewjackswann**
#59 
#56

### CODE REVIEW

**Comment by matthewjackswann** [comment]
Just fixing grapples so they sync across. Hold off on merging

**Comment by alexelwood14** [comment]
> Just fixing grapples so they sync across. Hold off on merging

I'm also working on some netcode/UI fixes on this branch so pls wait for this also.

**Review by James-Millan — APPROVED** [review]
Tested the networking myself on the VRs and I couldn't find a way to break anything. So I will approve these changes.

**Review by uq20042 — APPROVED** [review]
All looks good and working on the VR headsets

**Comment by matthewjackswann** [comment]
closed #27 #56 #59

**Pull request merged**
