### PR TITLE
Procedural Pipeline generates buildings locked to terrain

### LINKED ISSUE #53: Building Mass Generator Node

### PR DESCRIPTION
**Pull request by James-Millan**
Changes
- Created a Node editor pipeline that allows us to modularise task in a pipeline by implementing a class.
- Obtain a bounding box from longitude / latitude coordinates
- Get elevation data from bounding box
- Get satellite imagery in this bounding box from bing (will not be used in final product)
- Get building data nodes and ways from Kumi Overpass API
- Combine the points into a building mesh using a triangulation algorithm
- Convert the building meshes into Gameobjects with their real names if they exist
- Lock these buildings to the correct elevation in the terrain and have the correct height

Closes #53 , #46, #55, #52, #51, #48, #16, #52, #22, #55, #25

### CODE REVIEW

**Comment by James-Millan** [comment]
IMPORTANT, before reviewing this pull request please ensure that the code runs correctly locally. Run the pipeline on Bristol and make sure you get the expected output

**Review by uq20042 — APPROVED** [review]
Pipeline is working correctly. 
Only notes are the URP package isn't installed so rendering isn't working and we should probably merge the two asset folders at some point.

**Comment by uq20042** [comment]
Just looking through the repo now, a lot of the files are also in weird places from the merge. All the materials are in the Audio folder, the scripts are in the Models folder etc.
Easy to fix though and everything still works.

**Comment by James-Millan** [comment]
> Just looking through the repo now, a lot of the files are also in weird places from the merge. All the materials are in the Audio folder, the scripts are in the Models folder etc. Easy to fix though and everything still works.

We'll fix these before the merge

**Pull request merged**
